### ISSUE TITLE
Receiving 'KeyError: tool' when trying to run commands to observe agents (report.py & trades.py)

### ISSUE THREAD

**Issue by VinceLindsey** [valory-xyz/trader-quickstart#172]
Traceback (most recent call last):
  File "/Users/[redacted]/Documents/GitHub/trader-quickstart/trader/../report.py", line 212, in <module>
    mech_statistics = trades.get_mech_statistics(mech_requests)
  File "/Users/[redacted]/Documents/GitHub/trader-quickstart/trades.py", line 757, in get_mech_statistics
    if mech_request["ipfs_contents"]["tool"] in IRRELEVANT_TOOLS:
KeyError: 'tool'

**Comment by DavidMinarsch** [comment]
I checked against current `main` (https://github.com/valory-xyz/trader-quickstart/commit/c96722a474d04342edec490ddc6eae5cae99ee8f) and cannot replicate this. What commit are you on and what sequence of steps led to this?

**Comment by VinceLindsey** [comment]
I am on commit c96722a as well, working on my branch. Everything was working fine before I upgraded to v0.11.3. I can run and stop the service fine, but whenever I run `cd trader; poetry run python ../report.py; cd ..` or `cd trader; poetry run python ../trades.py MY_SAFE_ADDRESS; cd ..`, I receive that message.

**Comment by jmoreira-valory** [comment]
I haven't been able to replicate it locally either. However a fix to add guard clauses has been implemented to prevent the script from crashing: https://github.com/valory-xyz/trader-quickstart/pull/187
