### ISSUE TITLE
Include terminating the service in the unstaking flow

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/trader-quickstart#174]
Currently, the script only unstakes the service from the staking contract in the unstaking flow.

The service is still deployed and therefore operator and service owner deposits remain staked on the service NFT.

The unstaking flow should also terminate the service so that the user gets their OLAS deposits back without requiring any further steps from the user.

See [here](https://discord.com/channels/899649805582737479/1169275451089367131/1193293843932659774) for an example

**Comment by jmoreira-valory** [comment]
I assume you mean "Currently, the script only unstakes the service from the staking contract in the **update flow** ~~unstaking flow~~."
