### ISSUE TITLE
script still has issues with registration flow

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/trader-quickstart#203]
Issues reported:

- https://discord.com/channels/899649805582737479/1169275451089367131/1200595791400677426

**Comment by jmoreira-valory** [comment]
This references the following error:

```
-----------------------------------------
Checking Autonolas Protocol service state
-----------------------------------------
Updated 'AGENT_ID=14' in ../.trader_runner/.env
Checking balance of owner/operator's address (minimum required 0.0500 DAI):
  
Address: 0xC545679dB1D973F07bb20Cb24870B3E8Df7328BE
Balance: 0.0881 DAI
OK.

[Service owner] Minting your service on the Gnosis chain...
The currently activated Python version 3.12.1 is not supported by the project (<3.11,>=3.8).
Trying to find and use a compatible version. 
Using python3.8 (3.8.18)
The currently activated Python version 3.12.1 is not supported by the project (<3.11,>=3.8).
Trying to find and use a compatible version. 
Using python3.8 (3.8.18)
Error: Component mint failed with following error; ChainTimeoutError(Timed out when waiting for transaction to go through)
```

Unable to replicate it. If it re-occurs can increase retries on file `utils.py`
The issue occurs on `raise ChainTimeoutError("Timed out when waiting for transaction to go through")`

This issue is related to https://github.com/valory-xyz/trader-quickstart/issues/151

**Comment by dagacha** [comment]
One possible cause will be solved with https://github.com/valory-xyz/trader-quickstart/issues/151 

I'm going to close this issue since it has not been observed in our tests after the latest release.
